### ISSUE TITLE
Wireframes for FSP analytics web application

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-analytics-fsp#1]
Hi @krkwesiga - based on your initial design at http://hot.laboremus.nl I would suggest to move the text and options/filters box to the bottom where currently OSMA displays results and charts. See below:

![screen shot 2017-06-06 at 22 50 34](https://user-images.githubusercontent.com/10201533/26864096-0ab2eb36-4b0b-11e7-8374-a09b5ade080f.jpg)

We should also add the entry point in the top menu, with submenus (drop-down) for each of the four types of analysis.

Please update the live interactive wireframes and let's discuss on Monday.

cc @PaulUithol

**Comment by PaulUithol** [comment]
@benjaminug @krkwesiga could you please start updating issues/adding content here?

**Comment by benjaminug** [comment]
Update wireframes have been pushed. 
@PaulUithol i am back and will be updating the issues. Sorry about the delays.
